baseURL = "https://datasciencebox.org//"
title = "Data Science in a Box"
copyright = "&copy; 2018 RStudio"
theme = "hugo-theme-learn"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Languages
[languages.en]
  languageCode = "en-us"

# Outputs
[outputs]
  home = [ "HTML", "RSS", "JSON"]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML", "RSS" ]
  taxonomyTerm = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true
  
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
